# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-23 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0002_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
